[build]
  base = "/"  # Root of your monorepo
  publish = "dist/client/browser"  # Change this to your frontend output directory
  command = "turbo run build --filter=client"  # Change this based on your frontend build command

[[plugins]]
  package = "@netlify/plugin-monorepo"

# Optional: Redirects (if using SSR or API routes)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
